name: fundamakers
description: A new Flutter project.


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  animated_text_kit:
  pinput: ^4.0.0
  http: ^1.1.0
  intl: ^0.19.0
  image_picker: ^1.0.7
  flutter_polls: ^0.1.6
  flutter_pdfview: ^1.4.0
  dio: ^5.7.0
  google_fonts: ^5.1.0
  flutter_rating_bar: ^4.0.1
  percent_indicator:
  youtube_player_iframe: ^4.0.4
  flutter_widget_from_html: ^0.14.11
#  url_strategy: ^0.2.0
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  vimeo_player_flutter: ^0.1.0
  url_launcher: ^6.2.4
  razorpay_flutter: ^1.3.6
  connectivity_plus: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

flutter:


  uses-material-design: true


  assets:
    - assets/
    - assets/logo/
    - assets/images/
    - assets/icons/

